### PR TITLE
Fix issue #2 by supporting Android on the example

### PR DESCRIPTION
**Pull request by guilhermebruzzi**
By using https://www.npmjs.com/package/react-native-prompt and RN Alert: https://facebook.github.io/react-native/docs/alert.html to replace AlertIOS I've created a single example with index.android.js and index.ios.js importing a new App.js file.

I've also updated all package.json versions to make sure the example is updated.

### CODE REVIEW

**Comment by davideast** [comment]
Wow @guilhermebruzzi! This is awesome! Give me a bit to review, but thank you so much!

**Comment by guilhermebruzzi** [comment]
@davideast Hi David, did you had a chance to look at this PR? Thanks in advance!

**Comment by eladcandroid** [comment]
@davideast Can you please merge it?

**Comment by skv-headless** [comment]
@davideast please 🙏

**Pull request closed without merging**
